version_base: "0.0"

training:
  epochs: 300
  batch_size: 1
  lr: 1e-5
  max_grad_norm: 1.0
  mixed_precision: "bf16"
  enable_cfg: true
  adv_clip_max: 5
  clip_range: 1e-4
  ckpt_dir: "my_ckpt"
  inner_epochs: 1
  save_ckpt_every_epoch: 20
  gradient_accumulation_steps: 8

lora:
  enable: false
  rank: 16

sample:
  num_inference_steps: 10
  guidance_scale: 4.5
  num_prompts: 1
  batch_size: 1
  num_trees: 1
  noise_level: 0.7
  fixed_initial_noise: false
  remove_timestep: 1

env:
  model_name: "stabilityai/stable-diffusion-3.5-medium"
  pipeline: "StableDiffusion3"
  reward_model: "hpsv2"

data:
  prompt_path: "./prompts.txt"
  height: 512
  width: 512

run_name: "base"

tree:
  enable: true
  w: 4
  s: 1
  tou: 50
  k: 2
  use_ode: true
  loss_agg: "sum"